[package]

name = "chess-ai"
version = "0.1.0"
edition = "2021"
authors = [
    "Galitan-dev <galitan.dev@gmail.com>"
]

[[bin]]
name = "chess-ai"

[dependencies]
find_folder = "0.3.0"
gfx_core = "0.9.2"
piston_window = "0.126.0"
