[package]

name = "chess-ai"
version = "0.1.0"
authors = ["Galitan-dev <galitan.dev@gmail.com>"]

[[bin]]
name = "chess-ai"

[dependencies]
piston_window = "0.127.0"
anyhow = "1.0.69"
num-derive = "0.3.3"
num = "0.4.0"
num-traits = "0.2.15"
concat-arrays = "0.1.2"
find_folder = "0.3.0"
